# Generated by Django 4.2 on 2024-08-28 13:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0005_auto_20211104_0957"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="product",
            new_name="store_produ_id_2abda1_idx",
            old_fields=("id", "slug"),
        ),
    ]
